### ISSUE TITLE
NameError: name 'StrictBytes' is not defined

### ISSUE THREAD

**Issue by abhijitnarvekar** [cashfree/cashfree-pg-sdk-python#59]
get this error when testing integration : 

File "/home/abhijit/.local/lib/python3.8/site-packages/cashfree_pg/api_client.py", line 2080, in Cashfree
    def PGesUploadVendorsDocs(self, x_api_version : Annotated[StrictStr, Field(..., description="API version to be used. Format is in YYYY-MM-DD")] = None, vendor_id : Annotated[StrictStr, Field(..., description="The id which uniquely identifies your vendor.")] = None, x_request_id : Annotated[Optional[StrictStr], Field(description="Request id for the API call. Can be used to resolve tech issues. Communicate this in your tech related queries to cashfree")] = None, x_idempotency_key : Annotated[Optional[StrictStr], Field(description="An idempotency key is a unique identifier you include with your API call. If the request fails or times out, you can safely retry it using the same key to avoid duplicate actions.  ")] = None, doc_type : Annotated[Optional[StrictStr], Field(description="Mention the type of the document you are uploading. Possible values: UIDAI_FRONT, UIDAI_BACK, UIDAI_NUMBER, DL, DL_NUMBER, PASSPORT_FRONT, PASSPORT_BACK, PASSPORT_NUMBER, VOTER_ID, VOTER_ID_NUMBER, PAN, PAN_NUMBER, GST, GSTIN_NUMBER, CIN, CIN_NUMBER, NBFC_CERTIFICATE. If the doc type ends with a number you should add the doc value else upload the doc file.")] = None, doc_value : Annotated[Optional[StrictStr], Field(description="Enter the display name of the uploaded file.")] = None, file : Annotated[Optional[Union[StrictBytes, StrictStr]], Field(description="Select the document that should be uploaded or provide the path of that file. You cannot upload a file that is more than 2MB in size.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
NameError: name 'StrictBytes' is not defined

**Comment by suhas-cashfree** [comment]
Let me check this and get back to you.
Are you using this upload docs API ?

**Comment by suhas-cashfree** [comment]
Can you try version 4.1.3 and let us know

**Comment by abhijitnarvekar** [comment]
I am not using the API. This error message pops up when i call the
createOrder method, during resolving the imports in Python3.8.

**Comment by suhas-cashfree** [comment]
Can you try new version 4.1.3 ?

**Comment by abhijitnarvekar** [comment]
Worked this time with the latest version. Thanks and close this issue.

**Comment by suhas-cashfree** [comment]
Thanks for pointing it out. Closing this for now. Please raise a new issue, if it still persists
